# Étape de build
FROM node:18-slim AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-slim

WORKDIR /app

COPY --from=builder /app/dist /app/dist

EXPOSE 5173

RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "5173"]
