FROM node:18-bullseye AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

RUN npm run build

FROM node:18-bullseye

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 4000

CMD ["sh", "-c", "npm run db:migrate:prod && node dist/server.js"]
