name: Deploy on production

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GTHB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Backend
        run: |
          docker build -t ghcr.io/matteodinville/agileboard-backend:latest -f server/Dockerfile-prod server
          docker push ghcr.io/matteodinville/agileboard-backend:latest

      - name: Build and push Frontend
        run: |
          docker build -t ghcr.io/matteodinville/agileboard-frontend:latest -f client/Dockerfile-prod client
          docker push ghcr.io/matteodinville/agileboard-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "${{ secrets.GTHB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            cd ~/app/agileboard/back
            docker-compose pull
            docker-compose run --rm backend npx prisma migrate deploy
            docker-compose up -d --remove-orphans

            cd ~/app/agileboard/front
            docker-compose pull
            docker-compose up -d --remove-orphans

            docker image prune -f
