name: CI

on:
  pull_request:
    branches: [develop, main]
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    if: >
      github.event_name == 'pull_request' && (
        (github.base_ref == 'develop' && startsWith(github.head_ref, 'FT-')) ||
        (github.base_ref == 'main' && github.head_ref == 'develop')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      - name: Backend - install, lint, test, build
        working-directory: server
        run: |
          npm ci
          npm run lint
          npm test
          npm run build

      - name: Frontend - install, lint, test, build
        working-directory: client
        run: |
          npm ci
          npm run lint
          npm test
          npm run build
